#!/bin/bash
########################## Virtualenv: ##########################
install_dir="${PWD}" #update install directory
source "${install_dir}/env/bin/activate"
cd ${install_dir}

########################## Functions: ##########################
exec_mail(){
    echo "Sending mail $a_flag"
    python email.py
    exit 0
}

print_usage() {
  printf "Usage: ..."
  exit 1
}

########################## Commandline arguments: ##########################
a_flag=''
b_flag=''
files=''
verbose='false'

while getopts 'abf:v' flag; do
  case "${flag}" in
    a) a_flag='true' ;;
    b) b_flag='true' ;;
    f) files="${OPTARG}" ;;
    v) verbose='true' ;;
    *) print_usage;;
    #    exit 1 ;;
  esac
  exec_mail
done